# Site settings
title: Arya Boudaie's Personal Site
description: >
  The personal site for Arya Boudaie, with his blog, portfolio, educational resources,
  and other various things.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.aryaboudaie.com" # the base hostname & protocol for your site

author:
  fullname: Arya Boudaie
  github: misingnoglic
  disqus: aryab-log
  linkedin: aboudaie
  twitter: misingnoglic
  youtube: windowsforvista
  spotify: misingnoglic
  mailinglistlink: https://goo.gl/forms/jzaFhUpZ6x17oOJh2

google_analytics: UA-109265709-1

# Syntax highlighting
highlightstyle: 'darkula'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: rouge
markdown: kramdown
